language: php

php:
   - 5.6
   - 7.0
   - 7.1
   - hhvm
   - nightly

services:
   - mysql

sudo: false

cache:
   directories:
      - vendor

branches:
   only:
      - master

notifications:
   email: true

before_install:
   - mysql -e 'CREATE DATABASE video_game_inventory;'

install:
   - composer install --no-dev --quiet

script: phpunit -c phpunit.xml --coverage-text